### ISSUE TITLE
README Feedback

### ISSUE THREAD

**Issue by StefanGerrits2** [sarkis1997/functional-programming#1]
Readme:
- Geef je concept een naam
- Requirements? Welke requirements?
- Voeg feature lijst toe
- Voeg query toe (eventueel met een korte uitleg en een link naar een wiki pagina die hier meer over uitlegt)
- Je kan ook nog een beschrijving van de opdracht toevoegen
- Klopt de install guide? Werkt de lokale development server?

**Comment by sarkis1997** [comment]
All done💪🏼
