### ISSUE TITLE
Wiki feedback

### ISSUE THREAD

**Issue by StefanGerrits2** [sarkis1997/functional-programming#2]
## Menu:

Goed dat je voor elke dag een andere pagina heb gemaakt (een nadeel is wel dat de lezer erg vaak moet klikken).

## Inhoud van de pagina's:

Sommige dagen van je logboek zijn niet erg uitgebreid. 
* Cleaned dataset - pagina ziet er goed uit. Alles is uitgebreid stap voor stap beschreven. 
* Functional programming - Deze pagina mag wel iets uitgebreider. Laat voorbeelden zien wat functional programming is, en wat niet (stukken code).

Er is geen duidelijke "Transforming" pagina.

## Overig

* Nog geen live link.
* Nog geen lijstje met sources / credits.

**Comment by sarkis1997** [comment]
Thanks!
