### ISSUE TITLE
Code feedback

### ISSUE THREAD

**Issue by StefanGerrits2** [sarkis1997/functional-programming#3]
Goede mapstructuur.
Goed gebruik gemaakt van functions exporteren en importeren

In `fetchFunction.js` heb je dit staan:
````
let dataRaw = data.results.bindings;
return dataRaw;
````
Volgens mij kan je ook dit doen:
````
return let dataRaw = data.results.bindings`
````

Queries staan goed apart in een losse file.
Je code is goed functioneel opgebouwd.
Hier en daar kun je nog code comments plaatsen, bijvoorbeeld in `d3-viz.js`.

**Comment by sarkis1997** [comment]
Comments toegevoegd in gehele project.\
`return let dataRaw = data.results.bindings` lijkt niet te werken.\
Ik laat de code voor nu zoals die is.
